title: "Tingan's Blog"
email:
description: “Talk is cheap. Show me the code.” --- Hobby projects to make the world better.
author: Tingan Tang
baseurl: ""
url: "https://tingan.github.io"

# Social Profiles
twitter_username:
github_username: tingan
facebook_username:
instagram_username:
linkedin_username: tingan-tang-44183aa

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
